namespace MPC_MassPropertiesCalculator_MAUIapp
{
    public partial class App : Application
    {
        public App()
        {
            //Register Syncfusion license
            Syncfusion.Licensing.SyncfusionLicenseProvider.RegisterLicense("Mgo+DSMBaFt/QHRqVVhjVFpFdEBBXHxAd1p/VWJYdVt5flBPcDwsT3RfQF9iS3xbdk1hXXpbdHBcRw==;Mgo+DSMBPh8sVXJ0S0J+XE9HflRDX3xKf0x/TGpQb19xflBPallYVBYiSV9jS3xSdEdrWXdcdHFQQmZZUA==;ORg4AjUWIQA/Gnt2VVhkQlFadVdJXGFWfVJpTGpQdk5xdV9DaVZUTWY/P1ZhSXxRd0dhUX9WcnBQQ2RUUUU=;ODMwNTU1QDMyMzAyZTM0MmUzMFZ2bzJobi9OMTdURDBOVjhwMnVNUjMyRkVYNEp5QkZKNnd1Nit3TXhnVE09;ODMwNTU2QDMyMzAyZTM0MmUzMFNuM0twei94ei9sdDBSRGFLYlFqUFdyK0g2VGgwdzZRSk40RGlIU1dhdVE9;NRAiBiAaIQQuGjN/V0Z+WE9EaFxKVmJLYVB3WmpQdldgdVRMZVVbQX9PIiBoS35RdERhW3deeHZRQ2VZWUV3;ODMwNTU4QDMyMzAyZTM0MmUzMEFKVE56NzJpOG1ZcU15cVJYQXgwM3RqbTNSZ2E5dEJRb2tJUG4xVVJUajg9;ODMwNTU5QDMyMzAyZTM0MmUzMGVKOG9iTFBoSDQyWUxIQVpUZTN6NUo3NTEzMk5hQ3lWNStHWUtjV2RBeEk9;Mgo+DSMBMAY9C3t2VVhkQlFadVdJXGFWfVJpTGpQdk5xdV9DaVZUTWY/P1ZhSXxRd0dhUX9WcnBQQ2ZUV0c=;ODMwNTYxQDMyMzAyZTM0MmUzMFVYclNWOUlCbThieXRmWnNVWlczZndUKzFWTXFPdGZhR2FjV1dCem5RdUE9;ODMwNTYyQDMyMzAyZTM0MmUzMGxZU2I0b0VUNnNVZm1vdVplZXJITWs3RDVQN1VacG5ydWlRaEZyZ25WNk09;ODMwNTYzQDMyMzAyZTM0MmUzMEFKVE56NzJpOG1ZcU15cVJYQXgwM3RqbTNSZ2E5dEJRb2tJUG4xVVJUajg9 ");

            InitializeComponent();

            MainPage = new AppShell();
        }
    }
}