# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# This continuous integration pipeline is triggered anytime a user pushes code to the repo.
# This pipeline builds the Wpf project, runs unit tests, then saves the MSIX build artifact.
name: NET 6.0 CI

# Trigger on every master branch push and pull request
on:
  push:
    branches:
      - master

jobs:

  build:
    # since MSIX cam bundle all target platforms, we don't need a matrix to build multiple TFMs
    strategy:
      matrix:
        targetplatform: [x64] # was [x86, x64]

    runs-on: windows-2022
